spring:
  application:
    name: pwa_saas_server

  datasource:
    name: db_pwa_saas
    url: jdbc:mysql://localhost:3306/db_pwa_saas
    username: root
    password: 1234qwer
    driver-class-name: com.mysql.cj.jdbc.Driver

#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password: 123456
#      database: 0
#      lettuce:
#        pool:
#          max-idle: 16
#          max-active: 32
#          min-idle: 8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pwa.saas_server.data

logging:
  level:
    com:
      event.report: DEBUG